# Generated by Django 5.2 on 2025-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.IntegerField(blank=True, db_column='Codigo_Articulo', null=True)),
                ('tipo_insumo', models.CharField(db_column='Tipo_Insumo', max_length=250)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=70, null=True)),
                ('inventario_total', models.IntegerField(blank=True, db_column='Inventario_Total', null=True)),
                ('inventario_entrega', models.IntegerField(blank=True, db_column='Inventario_Entrega', null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': True,
            },
        ),
    ]
